using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using WeeSpurts.Environment;

namespace WeeSpurts.Editor
{
    /// <summary>
    /// Builds THUNDER LANES — the second venue greybox — from
    /// <see cref="ThunderLanesLayout"/>. Read that config's class comment first:
    /// it holds the design thesis, and these numbers are meaningless without it.
    ///
    /// Menu:
    ///   WeeSpurts -> 2 Build New Scene -> Thunder Lanes Playable    [start here]
    ///   WeeSpurts -> 3 Modify Open Scene -> Add Thunder Lanes Geometry
    ///
    /// WHY "PLAYABLE" IS A COPY, NOT A FRESH SCENE. The real lane, pins, ball
    /// and BowlingGame are code-generated by GreyboxSceneBuilder, which only
    /// knows how to make a WHOLE new scene — there is no "add a lane to this
    /// scene" entry point, and this script is not allowed to rewrite it. So the
    /// playable build OPENS TestVenue.unity (which already has all of that plus
    /// a working roaming Player), immediately SAVES IT UNDER A NEW NAME, and
    /// only then swaps the venue. TestVenue.unity itself is never written to.
    /// The playable lane does not move: it is x = 0 by definition of the
    /// coordinate frame, so the new venue is built AROUND the existing lane
    /// rather than the lane being rebuilt inside the new venue.
    ///
    /// EVERYTHING IT CREATES lives under one root, so the whole venue is one
    /// tickbox, and a re-run REBUILDS that root from scratch rather than merging
    /// into a stale previous run.
    ///
    /// SAFETY IS ENFORCED IN CODE, NOT BY DISCIPLINE: the approach band is
    /// audited on every run and the build fails loudly if anything — collider,
    /// renderer OR anchor — lands where the throw camera lives.
    /// </summary>
    public static class ThunderLanesBuilder
    {
        private const string ProjectRoot = "Assets/_Project";
        private const string LayoutAssetPath = ProjectRoot + "/ScriptableObjects/ThunderLanesLayout.asset";
        private const string ScenePath = ProjectRoot + "/Scenes/ThunderLanes.unity";
        private const string SourceScenePath = ProjectRoot + "/Scenes/TestVenue.unity";
        private const string RootName = "ThunderLanes";
        private const string LegacyVenueRoot = "AlleyGreybox";

        /// <summary>ThrowCamera.ConfigureAimView's Z, mirrored because this script may not modify it.</summary>
        private const float KnownAimCameraZ = -3.7f;

        /// <summary>Bounds.Intersects is TRUE for merely touching bounds, and bands share exact edges by construction.</summary>
        private const float AuditEpsilon = 0.002f;

        private static readonly List<Collider> CreatedColliders = new List<Collider>();
        private static readonly List<Collider> WalkableColliders = new List<Collider>();
        private static readonly List<Renderer> CreatedRenderers = new List<Renderer>();
        private static readonly List<Transform> CreatedAnchors = new List<Transform>();
        private static readonly List<string> Report = new List<string>();

        // ============================================================ menu

        [MenuItem("WeeSpurts/2 Build New Scene/Thunder Lanes Playable")]
        public static void BuildPlayableScene()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                Debug.Log("[ThunderLanes] Cancelled — the open scene has unsaved changes.");
                return;
            }

            if (AssetDatabase.LoadAssetAtPath<SceneAsset>(SourceScenePath) == null)
            {
                Debug.LogError($"[ThunderLanes] Cannot find {SourceScenePath}. The playable build copies that " +
                               "scene because it already contains the code-generated lane, pins, ball and a " +
                               "working roaming Player. Use 'Build Into Current Scene' instead.");
                return;
            }

            // Open the donor, then IMMEDIATELY save it under the new name. Every
            // edit after this line lands on ThunderLanes.unity, never TestVenue.
            Scene scene = EditorSceneManager.OpenScene(SourceScenePath, OpenSceneMode.Single);
            EnsureFolder(ProjectRoot + "/Scenes");
            if (!EditorSceneManager.SaveScene(scene, ScenePath))
            {
                Debug.LogError("[ThunderLanes] Could not save the copy — aborting before anything is changed.");
                return;
            }

            ThunderLanesLayout layout = LoadOrCreateAsset<ThunderLanesLayout>(LayoutAssetPath);
            RetireLegacyVenue();
            BuildVenue(layout);
            RehomePlayer(layout);

            AssetDatabase.SaveAssets();
            EditorSceneManager.SaveScene(scene, ScenePath);

            Debug.Log($"[ThunderLanes] PLAYABLE scene built and saved to {ScenePath}. " +
                      "Press Play: you should spawn in the entrance, walk the concourse, and be able to " +
                      "reach the lane 6 kiosk to start a match. TestVenue.unity was not modified.");
        }

        [MenuItem("WeeSpurts/3 Modify Open Scene/Add Thunder Lanes Geometry")]
        public static void BuildIntoCurrentScene()
        {
            Scene scene = SceneManager.GetActiveScene();
            ThunderLanesLayout layout = LoadOrCreateAsset<ThunderLanesLayout>(LayoutAssetPath);

            RetireLegacyVenue();
            BuildVenue(layout);

            AssetDatabase.SaveAssets();
            EditorSceneManager.MarkSceneDirty(scene);

            // NOT auto-saved on purpose — look at it before it hits disk.
            Debug.Log($"[ThunderLanes] Built into '{scene.name}' under the '{RootName}' root. " +
                      "The scene is DIRTY and NOT saved — look first, then Ctrl+S to keep it.");
        }

        // =========================================================== build

        private static void BuildVenue(ThunderLanesLayout L)
        {
            CreatedColliders.Clear();
            WalkableColliders.Clear();
            CreatedRenderers.Clear();
            CreatedAnchors.Clear();
            Report.Clear();

            ValidateLayout(L);

            var existing = GameObject.Find(RootName);
            if (existing != null) Object.DestroyImmediate(existing);

            var root = new GameObject(RootName);
            var anchors = Group(root, "Anchors");
            Materials mats = LoadMaterials();

            BuildShell(root, L, mats);
            BuildLaneBank(root, L, mats);
            BuildPinsetterRoom(root, anchors, L, mats);
            BuildBallReturns(root, L, mats);
            BuildLanePits(root, anchors, L, mats);
            BuildConcourse(root, anchors, L, mats);
            BuildFrontages(root, anchors, L, mats);
            BuildCasino(root, anchors, L, mats);
            BuildArcade(root, anchors, L, mats);
            BuildEntry(root, anchors, L, mats);
            BuildRestrooms(root, anchors, L, mats);
            BuildCardSeller(root, anchors, L, mats);
            BuildCeilings(root, L, mats);

            AuditApproachBand(L);
            LogReport(L);
        }

        /// <summary>
        /// Hard checks that would otherwise become invisible bugs. These ERROR
        /// rather than silently nudging geometry — the same rule AlleyGreybox
        /// follows: never move something to make a check pass.
        /// </summary>
        private static void ValidateLayout(ThunderLanesLayout L)
        {
            if (L.ApproachDepth < Mathf.Abs(KnownAimCameraZ) + L.ApproachCameraMargin)
                Debug.LogError($"[ThunderLanes] ApproachDepth {L.ApproachDepth} is too shallow. The aim camera " +
                               $"sits at z = {KnownAimCameraZ}, so it must be at least " +
                               $"{Mathf.Abs(KnownAimCameraZ) + L.ApproachCameraMargin}.");

            if (L.LaneCount % 2 != 0)
                Debug.LogWarning($"[ThunderLanes] LaneCount {L.LaneCount} is ODD. Ball returns and pits are built " +
                                 "per PAIR, so the last lane gets neither.");

            if (L.PlayableLaneIndex > L.LaneCount)
                Debug.LogError($"[ThunderLanes] PlayableLaneIndex {L.PlayableLaneIndex} is past the end of a " +
                               $"{L.LaneCount}-lane bank.");

            if (L.PinDeckEndZ < L.BackdropLaneLength + 2.5f)
                Debug.LogWarning($"[ThunderLanes] PinDeckEndZ {L.PinDeckEndZ} is west of GreyboxSceneBuilder's " +
                                 $"backstop at {L.BackdropLaneLength + 2.5f} — the pinsetter room will overlap it.");

            if (L.ConcoursePinchWidth < L.MinPrimaryWidth)
                Debug.LogWarning($"[ThunderLanes] The concourse pinch ({L.ConcoursePinchWidth}m) is under your own " +
                                 $"primary-route minimum ({L.MinPrimaryWidth}m).");
        }

        // ------------------------------------------------------------- shell

        private static void BuildShell(GameObject root, ThunderLanesLayout L, Materials m)
        {
            var shell = Group(root, "Shell");
            float t = L.WallThickness;
            float h = L.MaxCeiling;

            // THE FLOOR IS TILED AROUND THE PITS, NOT LAID OVER THEM.
            //
            // The first version of this laid ONE slab across the whole footprint
            // and let the pits sit "under" it. That does not work and it is worth
            // saying why: a pit floor 0.4m down is then covered by a solid
            // collider at y=0, so it is invisible AND unreachable, and the pit
            // furniture ends up standing on the main floor looking like
            // mushrooms. AlleyGreyboxBuilder already learned this — same fix.
            //
            // Three pieces along Z, and the middle one is broken up in X so the
            // pit footprints are genuinely open holes.
            Slab(shell, "Floor_West", L.RoomXMin, L.RoomXMax, L.RoomZMin, L.PitZMin,
                 -0.05f, 0.05f, m.Carpet, collider: true, walkable: true);
            Slab(shell, "Floor_East", L.RoomXMin, L.RoomXMax, L.PitZMax, L.RoomZMax,
                 -0.05f, 0.05f, m.Carpet, collider: true, walkable: true);

            float cursor = L.RoomXMin;
            for (int p = 0; p < L.PairCount && L.BuildLanePits; p++)
            {
                int laneA = p * 2 + 1;
                float cx = (L.LaneCentreX(laneA) + L.LaneCentreX(laneA + 1)) * 0.5f;
                float gapMin = cx - L.PitWidth * 0.5f;
                float gapMax = cx + L.PitWidth * 0.5f;

                if (gapMin > cursor)
                    Slab(shell, $"Floor_PitBand{p}", cursor, gapMin, L.PitZMin, L.PitZMax,
                         -0.05f, 0.05f, m.Carpet, collider: true, walkable: true);
                cursor = Mathf.Max(cursor, gapMax);
            }
            if (cursor < L.RoomXMax)
                Slab(shell, "Floor_PitBandEnd", cursor, L.RoomXMax, L.PitZMin, L.PitZMax,
                     -0.05f, 0.05f, m.Carpet, collider: true, walkable: true);

            Slab(shell, "Wall_North", L.RoomXMin - t, L.RoomXMin, L.RoomZMin, L.RoomZMax, 0f, h, m.Wall, true);
            Slab(shell, "Wall_South", L.RoomXMax, L.RoomXMax + t, L.RoomZMin, L.RoomZMax, 0f, h, m.Wall, true);
            Slab(shell, "Wall_West", L.RoomXMin - t, L.RoomXMax + t, L.RoomZMin - t, L.RoomZMin, 0f, h, m.Wall, true);
            Slab(shell, "Wall_East", L.RoomXMin - t, L.RoomXMax + t, L.RoomZMax, L.RoomZMax + t, 0f, h, m.Wall, true);

            // The lane floor reads as wood, the rest as carpet. Floor MATERIAL is
            // half of how a real centre zones itself, so it is worth the slabs.
            Slab(shell, "Floor_ApproachTimber", L.LaneBankXMin, L.LaneBankXMax,
                 L.ApproachZMin, 0f, 0f, 0.02f, m.Lane, collider: false);
        }

        // -------------------------------------------------------- lane bank

        private static void BuildLaneBank(GameObject root, ThunderLanesLayout L, Materials m)
        {
            var bank = Group(root, "BackdropLanes");
            float gutter = L.BackdropGutterWidth;

            for (int i = 1; i <= L.LaneCount; i++)
            {
                if (i == L.PlayableLaneIndex) continue; // the real lane is code-generated

                float cx = L.LaneCentreX(i);
                var lane = Group(bank, $"Lane{i:00}");
                float half = L.LanePitch * 0.5f - gutter;

                Cosmetic(lane, "Surface", cx - half, cx + half, 0f, L.BackdropLaneLength, 0f, 0.02f, m.Lane);
                Cosmetic(lane, "Rail_N", cx - half - gutter, cx - half, 0f, L.BackdropLaneLength,
                         0f, L.BackdropRailHeight, m.Rail);
                Cosmetic(lane, "Rail_S", cx + half, cx + half + gutter, 0f, L.BackdropLaneLength,
                         0f, L.BackdropRailHeight, m.Rail);

                // Pin deck stand-in so the far end of the bank isn't a void.
                Cosmetic(lane, "PinDeck", cx - half, cx + half, L.BackdropLaneLength, L.PinDeckEndZ,
                         0f, 0.04f, m.Counter);
            }

            Report.Add($"lane bank: {L.LaneCount} lanes, pitch {L.LanePitch}m, playable = lane " +
                       $"{L.PlayableLaneIndex} at x=0, bank x {L.LaneBankXMin:F1} .. {L.LaneBankXMax:F1}");
        }

        private static void BuildPinsetterRoom(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var room = Group(root, "PinsetterRoom");
            float z0 = L.PinsetterZMin;
            float z1 = L.RoomZMax;
            float t = L.WallThickness;

            // Partition wall between the pin decks and the machine room, with a
            // mechanic's doorway at the NORTH end. Accessible (Tony's call), so
            // it is a real gap rather than a decorative line.
            float doorX0 = L.LaneBankXMin - 1.6f;
            float doorX1 = doorX0 + 1.1f;
            Slab(room, "Partition_W", L.RoomXMin, doorX0, z0 - t, z0, 0f, L.CeilingPinsetter, m.Block, true);
            Slab(room, "Partition_E", doorX1, L.LaneBankXMax, z0 - t, z0, 0f, L.CeilingPinsetter, m.Block, true);
            Slab(room, "Partition_Head", doorX0, doorX1, z0 - t, z0,
                 L.DoorHeight, L.CeilingPinsetter - L.DoorHeight, m.Block, true);

            // Machine blocks, one per lane — the industrial rhythm is the look.
            for (int i = 1; i <= L.LaneCount; i++)
            {
                float cx = L.LaneCentreX(i);
                Slab(room, $"Setter{i:00}", cx - 0.7f, cx + 0.7f, z0 + 0.6f, z0 + 2.6f, 0f, 1.9f, m.Machine, true);
            }

            // Mechanic's catwalk down the back, raised, the classic detail.
            Slab(room, "Catwalk", L.RoomXMin, L.LaneBankXMax, z1 - 1.4f, z1, 0f, 0.5f, m.Machine, true, walkable: true);

            Anchor(anchors, "Anchor_PinsetterDoor", (doorX0 + doorX1) * 0.5f, z0 - 0.8f, 0f, 0f);
            Anchor(anchors, "Anchor_PinsetterCatwalk", L.LaneCentreX(1), z1 - 0.7f, 0.5f, 180f);

            Report.Add($"pinsetter room: z {z0:F1} .. {z1:F1} ({L.PinsetterRoomDepth}m), ACCESSIBLE via a " +
                       "1.1m mechanic's door at the north end");
        }

        private static void BuildBallReturns(GameObject root, ThunderLanesLayout L, Materials m)
        {
            var band = Group(root, "BallReturns");
            float z0 = L.BallReturnZMin;
            float z1 = L.BallReturnZMax;

            for (int p = 0; p < L.PairCount; p++)
            {
                int laneA = p * 2 + 1;
                float cx = (L.LaneCentreX(laneA) + L.LaneCentreX(laneA + 1)) * 0.5f;
                var unit = Group(band, $"Return{p + 1:00}");

                Slab(unit, "Body", cx - 0.6f, cx + 0.6f, z0 + 0.2f, z1 - 0.2f, 0f, 0.85f, m.Machine, true);
                // Score console on a post — the thing you actually walk up to.
                Post(unit, "ConsolePost", cx, z0 + 0.35f, 0f, 0.07f, 1.0f, m.Machine, true);
                Slab(unit, "ConsoleScreen", cx - 0.35f, cx + 0.35f, z0 + 0.28f, z0 + 0.42f, 1.0f, 0.45f, m.Neon, false);
            }
        }

        // ----------------------------------------------------------- seating

        private static void BuildLanePits(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            if (!L.BuildLanePits) return;

            var band = Group(root, "LanePits");
            float z0 = L.PitZMin;
            float z1 = L.PitZMax;
            float y = -L.PitRecess;

            for (int p = 0; p < L.PairCount; p++)
            {
                int laneA = p * 2 + 1;
                float cx = (L.LaneCentreX(laneA) + L.LaneCentreX(laneA + 1)) * 0.5f;
                float x0 = cx - L.PitWidth * 0.5f;
                float x1 = cx + L.PitWidth * 0.5f;
                var pit = Group(band, $"Pit{p + 1:00}");

                float stepBand = L.PitStepCount * 0.3f;
                Slab(pit, "SunkenFloor", x0, x1, z0 + stepBand, z1, y - 0.02f, 0.02f, m.PitFloor, true, walkable: true);

                // Steps cut into the WEST edge, so you drop into the pit off the
                // concourse rather than climbing in from the lane side.
                for (int s = 0; s < L.PitStepCount; s++)
                {
                    float rise = L.PitRecess / (L.PitStepCount + 1);
                    float sy = -rise * (s + 1);
                    Slab(pit, $"Step{s + 1}", x0, x1, z0 + s * 0.3f, z0 + (s + 1) * 0.3f,
                         sy, 0.02f, m.PitFloor, true, walkable: true);
                }

                // Semicircle table approximated by a disc — greybox reads the
                // silhouette, not the arc (ArtGuide: flat colours, no detail).
                float tz = (z0 + z1) * 0.5f + 0.3f;
                Post(pit, "Table", cx, tz, y, L.PitTableRadius, 0.75f, m.Furniture, true);

                // Fixed swivel seats on posts, arced around the table's lane side.
                for (int s = 0; s < L.SwivelSeatsPerPit; s++)
                {
                    float tFrac = L.SwivelSeatsPerPit == 1 ? 0.5f : s / (float)(L.SwivelSeatsPerPit - 1);
                    float ang = Mathf.Lerp(200f, 340f, tFrac) * Mathf.Deg2Rad;
                    float sx = cx + Mathf.Cos(ang) * (L.PitTableRadius + 0.45f);
                    float sz = tz + Mathf.Sin(ang) * (L.PitTableRadius + 0.45f);
                    Post(pit, $"Swivel{s + 1}", sx, sz, y, 0.06f, 0.45f, m.Machine, true);
                    Post(pit, $"SwivelSeat{s + 1}", sx, sz, y + 0.45f, 0.22f, 0.1f, m.Furniture, true);
                }

                Anchor(anchors, $"Anchor_Pit{p + 1:00}", cx, z0 + stepBand + 0.6f, y, 0f);
            }

            Report.Add($"lane pits: {L.PairCount} sunken {L.PitRecess}m, {L.SwivelSeatsPerPit} swivel seats each, " +
                       $"gap between pits {(2f * L.LanePitch - L.PitWidth):F2}m (threshold)");
        }

        // --------------------------------------------------------- concourse

        private static void BuildConcourse(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var street = Group(root, "Concourse");
            float z0 = L.ConcourseZMin;
            float z1 = L.ConcourseZMax;

            // The street's own floor patch, purely so the material change reads.
            Cosmetic(street, "StreetFloor", L.RoomXMin, L.RoomXMax, z0, z1, 0.001f, 0.01f, m.StreetFloor);

            // Lounge clusters — two couches facing, low table between. NOT tied
            // to a lane: this is where you sit to watch someone ELSE bowl, which
            // is the whole walkable-alley hypothesis in furniture form.
            float plazaCentreX = (L.LaneBankXMin + L.LaneBankXMax) * 0.5f;
            float spacing = 5.0f;
            for (int c = 0; c < L.LoungeClusterCount; c++)
            {
                float cx = plazaCentreX + (c - (L.LoungeClusterCount - 1) * 0.5f) * spacing;
                float cz = (z0 + z1) * 0.5f;
                var cluster = Group(street, $"Lounge{c + 1:00}");

                float half = L.CouchFacingGap * 0.5f;
                Slab(cluster, "CouchA", cx - L.CouchLength * 0.5f, cx + L.CouchLength * 0.5f,
                     cz + half, cz + half + 0.7f, 0f, 0.42f, m.Furniture, true);
                Slab(cluster, "CouchA_Back", cx - L.CouchLength * 0.5f, cx + L.CouchLength * 0.5f,
                     cz + half + 0.55f, cz + half + 0.7f, 0.42f, 0.45f, m.Furniture, true);
                Slab(cluster, "CouchB", cx - L.CouchLength * 0.5f, cx + L.CouchLength * 0.5f,
                     cz - half - 0.7f, cz - half, 0f, 0.42f, m.Furniture, true);
                Slab(cluster, "CouchB_Back", cx - L.CouchLength * 0.5f, cx + L.CouchLength * 0.5f,
                     cz - half - 0.7f, cz - half - 0.55f, 0.42f, 0.45f, m.Furniture, true);
                Slab(cluster, "Table", cx - 0.55f, cx + 0.55f, cz - 0.35f, cz + 0.35f, 0f, 0.4f, m.Counter, true);

                Anchor(anchors, $"Anchor_Lounge{c + 1:00}", cx, cz, 0f, 0f);
            }

            // Ball racks and a polisher, at the lane end of the street where a
            // real house puts them — NOT stranded mid-floor.
            float rackZ = z1 - 1.0f;
            for (int r = 0; r < 2; r++)
            {
                float rx = plazaCentreX + (r == 0 ? -3.2f : 3.2f);
                Slab(street, $"BallRack{r + 1}", rx - 1.1f, rx + 1.1f, rackZ - 0.35f, rackZ + 0.35f,
                     0f, 1.15f, m.Machine, true);
            }

            Report.Add($"concourse: z {z0:F1} .. {z1:F1}, pinch {L.ConcoursePinchWidth}m -> plaza " +
                       $"{L.ConcoursePlazaWidth}m, {L.LoungeClusterCount} lounge clusters");
        }

        // --------------------------------------------------------- frontages

        private static void BuildFrontages(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var strip = Group(root, "Frontages");
            float zBack = L.FrontageZMin;   // staff side / rear
            float zFace = L.FrontageZMax;   // the street
            float counterZ0 = zFace - L.CounterDepth;

            // North to south along X, in the order you meet them walking in from
            // the south entrance: pro shop, shoe desk, snack, bar, casino.
            //
            // GAPS BETWEEN THEM MATTER. Butted together they merge into one 20m
            // white wall (which is exactly what the first build looked like).
            // A real parade of shopfronts has a gap you can step into between
            // each one — that is what makes them read as separate businesses
            // rather than one counter.
            const float FrontageGap = 1.4f;

            float x = L.RoomXMin + L.CasinoWidth + FrontageGap;   // casino owns the north end
            BuildCounter(strip, anchors, "Bar", x, x + L.BarWidth, counterZ0, zFace, L, m, m.Counter);
            x += L.BarWidth + FrontageGap;
            BuildCounter(strip, anchors, "Snack", x, x + L.SnackWidth, counterZ0, zFace, L, m, m.Counter);
            x += L.SnackWidth + FrontageGap;
            float shoeX0 = x;
            BuildCounter(strip, anchors, "ShoeDesk", x, x + L.ShoeDeskWidth, counterZ0, zFace, L, m, m.Counter);
            x += L.ShoeDeskWidth + FrontageGap;
            BuildCounter(strip, anchors, "ProShop", x, x + L.ProShopWidth, counterZ0, zFace, L, m, m.Counter);

            // Shoe cubby wall behind the desk — the one fixture that says
            // "bowling alley" faster than anything except the lanes.
            Slab(strip, "ShoeCubbies", shoeX0, shoeX0 + L.ShoeDeskWidth, zBack + 0.1f, zBack + 0.45f,
                 0f, 2.1f, m.Furniture, true);

            // ONE continuous back-of-house ribbon behind every counter, linking
            // cellar, dry store and staff room to a loading door at the south
            // end. In a real building this is a single spine — three separate
            // staff rooms is exactly what made the reference read as boxes.
            var boh = Group(root, "BackOfHouse");
            float bohZ0 = L.RoomZMin;
            float bohZ1 = L.BackOfHouseZMax;
            Slab(boh, "Partition", L.RoomXMin, L.RoomXMax, bohZ1 - L.WallThickness, bohZ1,
                 0f, L.CeilingBackOfHouse, m.Wall, true);
            Anchor(anchors, "Anchor_LoadingDoor", L.RoomXMax - 2f, (bohZ0 + bohZ1) * 0.5f, 0f, 90f);

            Report.Add($"frontages: bar/snack/shoe/proshop as shopfronts on the street, one BOH ribbon " +
                       $"z {bohZ0:F1} .. {bohZ1:F1}");
        }

        private static void BuildCounter(GameObject parent, GameObject anchors, string name,
                                         float x0, float x1, float z0, float z1,
                                         ThunderLanesLayout L, Materials m, Material mat)
        {
            var g = Group(parent, name);
            Slab(g, "Counter", x0, x1, z0, z1, 0f, L.CounterHeight, mat, true);
            // Back fitting, kept below eye height so the staff side stays visible
            // from the street — a frontage you can't see into reads as a wall.
            Slab(g, "BackFitting", x0, x1, L.FrontageZMin + 0.6f, L.FrontageZMin + 1.0f, 0f, 1.5f, m.Furniture, true);
            Anchor(anchors, $"Anchor_{name}", (x0 + x1) * 0.5f, z1 + 0.8f, 0f, 180f);
        }

        // ------------------------------------------------------------ casino

        private static void BuildCasino(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var g = Group(root, "Casino");
            float x0 = L.RoomXMin;
            float x1 = L.RoomXMin + L.CasinoWidth;
            float z0 = L.FrontageZMin;
            float z1 = L.FrontageZMax;
            float y = L.CasinoRise;

            Slab(g, "Platform", x0, x1, z0, z1, 0f, y, m.CasinoFloor, true, walkable: true);

            // TWO stair runs at opposite ends, not one. A single-access platform
            // is a dead end, and the circulation audit counts loops — two runs
            // means you can walk THROUGH the lounge instead of into it.
            BuildStair(g, "Stair_South", x1, z1 - 2.4f, L, m, alongZ: true);
            BuildStair(g, "Stair_North", x0 + 1.2f, z1, L, m, alongZ: false);

            // Wood balustrade around the open edges (Tony's call).
            float r = 0.08f;
            for (float bz = z0 + 0.4f; bz <= z1 - 0.4f; bz += 1.2f)
                Post(g, "RailPost", x1 - r, bz, y, r, 1.0f, m.Wood, true);
            Slab(g, "RailTop", x1 - 0.12f, x1, z0, z1 - 2.4f, y + 1.0f, 0.08f, m.Wood, true);

            // Slots along the north wall, felt table in the middle.
            for (int s = 0; s < 4; s++)
            {
                float sx = x0 + 0.9f + s * 1.2f;
                Slab(g, $"Slot{s + 1}", sx - 0.3f, sx + 0.3f, z0 + 0.3f, z0 + 0.9f, y, 1.7f, m.Machine, true);
            }
            Slab(g, "FeltTable", x0 + 1.4f, x0 + 3.5f, z0 + 2.6f, z0 + 4.0f, y, 0.85f, m.Felt, true);

            Anchor(anchors, "Anchor_Casino", (x0 + x1) * 0.5f, (z0 + z1) * 0.5f, y, 90f);
            Anchor(anchors, "Anchor_CasinoTable", (x0 + 1.4f + x0 + 3.5f) * 0.5f, z0 + 4.4f, y, 0f);

            Report.Add($"casino: raised +{L.CasinoRise}m, wood balustrade, TWO stair runs (walk-through, not a dead end)");
        }

        private static void BuildStair(GameObject parent, string name, float x, float z,
                                       ThunderLanesLayout L, Materials m, bool alongZ)
        {
            var s = Group(parent, name);
            float rise = L.CasinoRise / L.CasinoStepCount;
            for (int i = 0; i < L.CasinoStepCount; i++)
            {
                float y = rise * (i + 1);
                float off = L.CasinoStepRun * i;
                if (alongZ)
                    Slab(s, $"Step{i + 1}", x - 1.2f, x, z + off, z + off + L.CasinoStepRun,
                         y - rise, rise, m.Wood, true, walkable: true);
                else
                    Slab(s, $"Step{i + 1}", x + off, x + off + L.CasinoStepRun, z - 1.2f, z,
                         y - rise, rise, m.Wood, true, walkable: true);
            }
        }

        // ------------------------------------------------------------ arcade

        private static void BuildArcade(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            if (!L.BuildArcade) return;

            var g = Group(root, "Arcade");
            // South of the lane bank, level with the pit band — so it is the
            // FIRST thing glowing at you when you come through the doors and
            // step onto the street. An ALCOVE with its own mouth and its own
            // (low) ceiling; that drop is the whole effect.
            //
            // Deliberately NOT inside the concourse Z band: the street runs the
            // full 34m of the building and an alcove sitting in it would dam the
            // one route everybody uses.
            float x0 = L.LaneBankXMax + 1.0f;
            float x1 = L.LaneBankXMax + 8.0f;
            float z0 = L.PitZMin;
            float z1 = L.PitZMax;
            float t = L.WallThickness;

            // Alcove side walls, leaving a mouth on the street side.
            Slab(g, "Wall_W", x0 - t, x0, z0, z1 - 3.2f, 0f, L.CeilingArcade, m.Wall, true);
            Slab(g, "Wall_Back", x0 - t, x1, z0 - t, z0, 0f, L.CeilingArcade, m.Wall, true);

            // Cabinets down both walls, facing the aisle. The aisle is the clear
            // secondary route; the cabinets are what you stand at.
            int perSide = Mathf.Max(1, L.ArcadeCabinetCount / 2);
            for (int i = 0; i < perSide; i++)
            {
                float cz = z0 + 1.0f + i * (L.ArcadeCabinetWidth + 0.25f);
                Slab(g, $"Cab_W{i + 1}", x0 + 0.1f, x0 + 0.1f + L.ArcadeCabinetDepth,
                     cz, cz + L.ArcadeCabinetWidth, 0f, L.ArcadeCabinetHeight, m.Machine, true);
                Slab(g, $"Cab_E{i + 1}", x0 + 0.1f + L.ArcadeCabinetDepth + L.ArcadeAisleWidth,
                     x0 + 0.1f + 2f * L.ArcadeCabinetDepth + L.ArcadeAisleWidth,
                     cz, cz + L.ArcadeCabinetWidth, 0f, L.ArcadeCabinetHeight, m.Machine, true);
            }

            Anchor(anchors, "Anchor_Arcade", x0 + L.ArcadeCabinetDepth + L.ArcadeAisleWidth * 0.5f,
                   (z0 + z1) * 0.5f, 0f, 0f);

            Report.Add($"arcade: alcove x {x0:F1} .. {x1:F1}, ceiling {L.CeilingArcade}m " +
                       $"(vs {L.CeilingConcourse}m concourse — the drop IS the zoning), aisle {L.ArcadeAisleWidth}m");
        }

        // ------------------------------------------------------------- entry

        private static void BuildEntry(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var g = Group(root, "Entry");
            float cx = L.RoomXMax - 3.5f;
            // 3.2 rather than 2.5 so the rotated jambs clear the pro shop's back
            // fitting — an angled object needs more room than its own footprint.
            float cz = L.FrontageZMin + 3.2f;

            // THE one angled element. Rotated so your first frame on entering is
            // a diagonal across the whole floor — lane bank receding one way,
            // bar neon the other. Set EntryAngleDegrees to 0 and the building
            // immediately goes back to reading as a box.
            var vest = Group(g, "Vestibule");
            SlabRotated(vest, "Mat", new Vector3(cx, 0.01f, cz), new Vector3(4.5f, 0.02f, 3.0f),
                        L.EntryAngleDegrees, m.StreetFloor, collider: false);
            SlabRotated(vest, "Jamb_L", new Vector3(cx - 1.6f, L.DoorHeight * 0.5f, cz - 1.4f),
                        new Vector3(0.4f, L.DoorHeight, 0.4f), L.EntryAngleDegrees, m.Wall, collider: true);
            SlabRotated(vest, "Jamb_R", new Vector3(cx + 1.6f, L.DoorHeight * 0.5f, cz - 1.4f),
                        new Vector3(0.4f, L.DoorHeight, 0.4f), L.EntryAngleDegrees, m.Wall, collider: true);

            Anchor(anchors, "Anchor_Entrance", cx, cz + 1.4f, 0f, L.EntryAngleDegrees + 180f);
            Anchor(anchors, "Anchor_PlayerSpawn", cx - 1.0f, cz + 2.6f, 0f, L.EntryAngleDegrees + 180f);

            Report.Add($"entry: vestibule rotated {L.EntryAngleDegrees}deg at x {cx:F1}, z {cz:F1}");
        }

        private static void BuildRestrooms(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var g = Group(root, "Restrooms");
            // South-east corner, off the street and past the arcade — a long
            // walk from the doors, which is both realistic and where you
            // actually want them (near the lanes, not near the entrance).
            float x0 = L.RoomXMax - 5.0f;
            float x1 = L.RoomXMax - 0.5f;
            float z0 = L.PitZMin;
            float z1 = L.PitZMin + 4.0f;
            float t = L.WallThickness;

            Slab(g, "Wall_W", x0 - t, x0, z0, z1, 0f, L.CeilingFrontage, m.Wall, true);
            Slab(g, "Wall_N", x0, x1, z0 - t, z0, 0f, L.CeilingFrontage, m.Wall, true);
            Slab(g, "Divider", x0, x1, (z0 + z1) * 0.5f - t * 0.5f, (z0 + z1) * 0.5f + t * 0.5f,
                 0f, L.CeilingFrontage, m.Wall, true);

            Anchor(anchors, "Anchor_Restrooms", x0 - 1.2f, (z0 + z1) * 0.5f, 0f, 90f);
        }

        private static void BuildCardSeller(GameObject root, GameObject anchors, ThunderLanesLayout L, Materials m)
        {
            var g = Group(root, "CardSeller");
            // Off the NORTH WALKWAY, level with the far end of the pit band —
            // the deadest corner of the building, nothing else up there, no
            // reason to walk past it. You find it by accident and you have to
            // turn sideways to get in. DELIBERATE exemption from the 1.2m
            // threshold minimum, same reasoning AlleyLayout already recorded
            // for its card dealer alcove: the squeeze is the point.
            float x0 = L.RoomXMin;
            float x1 = x0 + 2.4f;
            float z1 = L.PitZMax;
            float z0 = z1 - L.CardSellerWidth;
            float t = L.WallThickness;

            Slab(g, "Wall_S", x0, x1, z0 - t, z0, 0f, L.CeilingFrontage, m.Wall, true);
            Slab(g, "Counter", x0 + 0.2f, x1 - 0.2f, z0 + 0.15f, z0 + 0.55f, 0f, 0.95f, m.Furniture, true);

            Anchor(anchors, "Anchor_CardSeller", (x0 + x1) * 0.5f, z0 + 0.75f, 0f, 180f);

            Report.Add($"card seller: {L.CardSellerWidth}m squeeze off the north walkway — under the " +
                       $"{L.MinThresholdWidth}m threshold minimum ON PURPOSE (exemption, like the alley's alcove)");
        }

        /// <summary>
        /// Ceiling planes per zone. THE most important thing in this file for
        /// making the place read as a real building rather than extruded rooms —
        /// you feel the height change walking from the concourse into the arcade.
        /// All under one group so you can switch the lot off to work top-down.
        /// </summary>
        private static void BuildCeilings(GameObject root, ThunderLanesLayout L, Materials m)
        {
            var g = Group(root, "Ceilings");

            // FULL-WIDTH Z BANDS, edge to edge, no gaps. The first version gave
            // each zone a plane only as wide as that zone, which left holes you
            // could see the skybox through — a ceiling with gaps reads as
            // unfinished, not as zoning. Bands overlap at their seams on
            // purpose; from below you simply see the lower one.
            Cosmetic(g, "Ceil_Frontage", L.RoomXMin, L.RoomXMax, L.RoomZMin, L.FrontageZMax,
                     L.CeilingFrontage, 0.1f, m.Ceiling);
            Cosmetic(g, "Ceil_Concourse", L.RoomXMin, L.RoomXMax, L.FrontageZMax, L.ConcourseZMax,
                     L.CeilingConcourse, 0.1f, m.Ceiling);
            Cosmetic(g, "Ceil_Lanes", L.RoomXMin, L.RoomXMax, L.ConcourseZMax, L.PinsetterZMin,
                     L.CeilingLanes, 0.1f, m.Ceiling);
            Cosmetic(g, "Ceil_Pinsetter", L.RoomXMin, L.RoomXMax, L.PinsetterZMin, L.RoomZMax,
                     L.CeilingPinsetter, 0.1f, m.Ceiling);

            if (L.BuildArcade)
                Cosmetic(g, "Ceil_Arcade", L.LaneBankXMax + 1f, L.LaneBankXMax + 8f,
                         L.PitZMin, L.PitZMax, L.CeilingArcade, 0.1f, m.Ceiling);
        }

        // ============================================================ audit

        /// <summary>
        /// The one hard safety check: NOTHING may exist in the approach band —
        /// not a collider, not a renderer, not an anchor — because that is where
        /// the throw camera lives. Same rule, and the same strictness, as
        /// AlleyGreyboxBuilder's approach check.
        /// </summary>
        private static void AuditApproachBand(ThunderLanesLayout L)
        {
            // The Y range is NOT floor-to-ceiling, and both ends are deliberate.
            // Bottom at 0.06 so the audit doesn't flag the floor slabs it just
            // laid (approach timber tops out at 0.02) — the floor is supposed to
            // be there. Top just under the ceiling so the ceiling plane at
            // exactly CeilingLanes doesn't false-positive: Bounds.Intersects
            // returns TRUE for merely touching bounds. Everything a camera could
            // actually hit lives between those two numbers.
            var band = new Bounds();
            band.SetMinMax(
                new Vector3(L.LaneBankXMin + AuditEpsilon, 0.06f, L.ApproachZMin + AuditEpsilon),
                new Vector3(L.LaneBankXMax - AuditEpsilon, L.CeilingLanes - 0.2f, -AuditEpsilon));

            int violations = 0;

            foreach (Collider c in CreatedColliders)
            {
                if (c == null || !band.Intersects(c.bounds)) continue;
                Debug.LogError($"[ThunderLanes] COLLIDER '{c.name}' is inside the approach band. " +
                               "Nothing may be built there — the throw camera lives in it.", c.gameObject);
                violations++;
            }

            foreach (Renderer r in CreatedRenderers)
            {
                if (r == null || !band.Intersects(r.bounds)) continue;
                Debug.LogError($"[ThunderLanes] RENDERER '{r.name}' is inside the approach band. A cosmetic box " +
                               "in the aim camera's face is as bad as a wall.", r.gameObject);
                violations++;
            }

            foreach (Transform a in CreatedAnchors)
            {
                if (a == null || !band.Contains(a.position)) continue;
                Debug.LogError($"[ThunderLanes] ANCHOR '{a.name}' is inside the approach band.", a.gameObject);
                violations++;
            }

            Report.Add(violations == 0
                ? "approach band: CLEAR (0 violations)"
                : $"approach band: {violations} VIOLATIONS — fix before playing");
        }

        private static void LogReport(ThunderLanesLayout L)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"[ThunderLanes] built — {L.RoomWidth:F1}m x {L.RoomDepth:F1}m, " +
                          $"{CreatedColliders.Count} colliders, {CreatedAnchors.Count} anchors.");
            sb.AppendLine($"  ceilings: lanes {L.CeilingLanes} / concourse {L.CeilingConcourse} / " +
                          $"frontage {L.CeilingFrontage} / arcade {L.CeilingArcade}");
            foreach (string line in Report) sb.AppendLine("  " + line);
            sb.AppendLine("  These numbers are INFORMATION, not defects. Walk it before changing any of them.");
            Debug.Log(sb.ToString());
        }

        // ========================================================= plumbing

        private static void RetireLegacyVenue()
        {
            var legacy = GameObject.Find(LegacyVenueRoot);
            if (legacy == null) return;
            Object.DestroyImmediate(legacy);
            Debug.Log($"[ThunderLanes] Removed the '{LegacyVenueRoot}' root from this scene — " +
                      "the two venues would occupy the same space.");
        }

        /// <summary>
        /// Move the existing roaming Player to the new entrance. Without this the
        /// copied scene spawns you wherever the old venue put you, which in the
        /// new layout is usually inside a wall.
        /// </summary>
        private static void RehomePlayer(ThunderLanesLayout L)
        {
            var player = GameObject.Find("Player");
            if (player == null)
            {
                Debug.LogWarning("[ThunderLanes] No 'Player' object found — run " +
                                 "WeeSpurts > 3 Modify Open Scene > Set Up Roaming Player, then re-run this build.");
                return;
            }

            Transform spawn = null;
            foreach (Transform a in CreatedAnchors)
                if (a != null && a.name == "Anchor_PlayerSpawn") spawn = a;

            if (spawn == null) return;

            // A CharacterController overwrites direct transform writes on its next
            // step, so it has to go off around the teleport — same lesson
            // PlayerAvatar.MoveToThrowingStance already learned.
            var cc = player.GetComponent<CharacterController>();
            bool wasEnabled = cc != null && cc.enabled;
            if (wasEnabled) cc.enabled = false;
            player.transform.SetPositionAndRotation(spawn.position + Vector3.up * 0.1f, spawn.rotation);
            if (wasEnabled) cc.enabled = true;

            Debug.Log($"[ThunderLanes] Player moved to the entrance at {spawn.position}.");
        }

        private struct Materials
        {
            public Material Carpet, StreetFloor, Wall, Block, Ceiling, CasinoFloor, PitFloor,
                            Counter, Furniture, Machine, Wood, Felt, Lane, Rail, Neon;
        }

        private static Materials LoadMaterials()
        {
            return new Materials
            {
                // That geometric bowling-alley carpet, as one flat dark colour —
                // greybox reads value, not pattern (ArtGuide).
                Carpet = LoadOrCreateMaterial("TL_CarpetMat", new Color(0.13f, 0.11f, 0.18f)),
                StreetFloor = LoadOrCreateMaterial("TL_StreetMat", new Color(0.20f, 0.18f, 0.24f)),
                Wall = LoadOrCreateMaterial("TL_WallMat", new Color(0.24f, 0.22f, 0.22f)),
                Block = LoadOrCreateMaterial("TL_BlockMat", new Color(0.42f, 0.42f, 0.40f)),
                Ceiling = LoadOrCreateMaterial("TL_CeilingMat", new Color(0.16f, 0.16f, 0.17f)),
                CasinoFloor = LoadOrCreateMaterial("TL_CasinoFloorMat", new Color(0.42f, 0.09f, 0.12f)),
                PitFloor = LoadOrCreateMaterial("TL_PitFloorMat", new Color(0.22f, 0.19f, 0.28f)),
                Counter = LoadOrCreateMaterial("TL_CounterMat", new Color(0.86f, 0.84f, 0.78f)),
                Furniture = LoadOrCreateMaterial("TL_FurnitureMat", new Color(0.45f, 0.28f, 0.18f)),
                Machine = LoadOrCreateMaterial("TL_MachineMat", new Color(0.16f, 0.16f, 0.18f)),
                Wood = LoadOrCreateMaterial("TL_WoodMat", new Color(0.52f, 0.34f, 0.17f)),
                Felt = LoadOrCreateMaterial("TL_FeltMat", new Color(0.09f, 0.35f, 0.18f)),
                Lane = LoadOrCreateMaterial("LaneMat", new Color(0.85f, 0.65f, 0.35f)),
                Rail = LoadOrCreateMaterial("RailMat", new Color(0.25f, 0.25f, 0.3f)),
                Neon = LoadOrCreateMaterial("TL_NeonMat", new Color(0.95f, 0.35f, 0.85f)),
            };
        }

        private static GameObject Group(GameObject parent, string name)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform);
            return go;
        }

        /// <summary>A box described by its EXTENTS, the way a floorplan describes it.</summary>
        private static GameObject Slab(GameObject parent, string name,
                                       float xMin, float xMax, float zMin, float zMax,
                                       float yBase, float height, Material mat, bool collider,
                                       bool walkable = false)
        {
            var centre = new Vector3((xMin + xMax) * 0.5f, yBase + height * 0.5f, (zMin + zMax) * 0.5f);
            var size = new Vector3(Mathf.Abs(xMax - xMin), height, Mathf.Abs(zMax - zMin));
            return MakeBox(parent, name, centre, size, Quaternion.identity, mat, collider, walkable);
        }

        private static GameObject SlabRotated(GameObject parent, string name, Vector3 centre, Vector3 size,
                                              float yaw, Material mat, bool collider, bool walkable = false)
        {
            return MakeBox(parent, name, centre, size, Quaternion.Euler(0f, yaw, 0f), mat, collider, walkable);
        }

        /// <summary>Slab with the collider stripped. CreatePrimitive ALWAYS attaches one,
        /// and anything purely visual becomes an invisible wall unless you remove it.</summary>
        private static GameObject Cosmetic(GameObject parent, string name,
                                           float xMin, float xMax, float zMin, float zMax,
                                           float yBase, float height, Material mat)
        {
            return Slab(parent, name, xMin, xMax, zMin, zMax, yBase, height, mat, collider: false);
        }

        private static GameObject Post(GameObject parent, string name, float x, float z,
                                       float yBase, float radius, float height, Material mat, bool collider,
                                       bool walkable = false)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            go.name = name;
            go.transform.SetParent(parent.transform);
            go.transform.position = new Vector3(x, yBase + height * 0.5f, z);
            // A cylinder mesh is 2 units tall and 1 across at scale 1.
            go.transform.localScale = new Vector3(radius * 2f, height * 0.5f, radius * 2f);
            var rend = go.GetComponent<Renderer>();
            rend.sharedMaterial = mat;
            CreatedRenderers.Add(rend);
            FinishCollider(go, collider, walkable);
            return go;
        }

        private static GameObject MakeBox(GameObject parent, string name, Vector3 centre, Vector3 size,
                                          Quaternion rotation, Material mat, bool collider, bool walkable)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.name = name;
            go.transform.SetParent(parent.transform);
            go.transform.position = centre;
            go.transform.rotation = rotation;
            go.transform.localScale = size;
            var rend = go.GetComponent<Renderer>();
            rend.sharedMaterial = mat;
            CreatedRenderers.Add(rend);
            FinishCollider(go, collider, walkable);
            return go;
        }

        private static void FinishCollider(GameObject go, bool keep, bool walkable)
        {
            var col = go.GetComponent<Collider>();
            if (col == null) return;

            if (keep)
            {
                CreatedColliders.Add(col);
                if (walkable) WalkableColliders.Add(col);
            }
            else
            {
                Object.DestroyImmediate(col);
            }
        }

        private static GameObject Anchor(GameObject parent, string name, float x, float z, float y, float yaw)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform);
            go.transform.position = new Vector3(x, y, z);
            go.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
            CreatedAnchors.Add(go.transform);
            return go;
        }

        private static Material LoadOrCreateMaterial(string name, Color color)
        {
            string path = ProjectRoot + "/Materials/" + name + ".mat";
            var existing = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (existing != null) return existing;

            // URP projects render "Standard" as pink; pick whichever exists.
            Shader shader = Shader.Find("Universal Render Pipeline/Lit");
            if (shader == null) shader = Shader.Find("Standard");

            var mat = new Material(shader) { color = color };
            EnsureFolder(ProjectRoot + "/Materials");
            AssetDatabase.CreateAsset(mat, path);
            return mat;
        }

        private static T LoadOrCreateAsset<T>(string path) where T : ScriptableObject
        {
            var existing = AssetDatabase.LoadAssetAtPath<T>(path);
            if (existing != null) return existing;

            EnsureFolder(System.IO.Path.GetDirectoryName(path).Replace('\\', '/'));
            var asset = ScriptableObject.CreateInstance<T>();
            AssetDatabase.CreateAsset(asset, path);
            return asset;
        }

        private static void EnsureFolder(string path)
        {
            string[] parts = path.Split('/');
            string current = parts[0]; // "Assets"
            for (int i = 1; i < parts.Length; i++)
            {
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }
    }
}
